/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author IDEAPAD FLEX 5i
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public admin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnDosen = new javax.swing.JLabel();
        mnMhs = new javax.swing.JLabel();
        mnMK = new javax.swing.JLabel();
        bLogOut = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        siDosen = new javax.swing.JMenuItem();
        siMhs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));

        mnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDosenMouseClicked(evt);
            }
        });

        mnMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMhsMouseClicked(evt);
            }
        });

        mnMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMKMouseClicked(evt);
            }
        });

        bLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut.jpg"))); // NOI18N
        bLogOut.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut-pressed.jpg"))); // NOI18N
        bLogOut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut-pressed.jpg"))); // NOI18N
        bLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOutActionPerformed(evt);
            }
        });

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin-home.jpg"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });

        jMenu2.setText("Edit Data");

        jMenuItem4.setText("Mata Kuliah");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("List Mahasiswa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("List Dosen");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("View Mode");

        siDosen.setText("Sign in as Dosen");
        siDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siDosenActionPerformed(evt);
            }
        });
        jMenu5.add(siDosen);

        siMhs.setText("Sign in as Mahasiswa");
        siMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siMhsActionPerformed(evt);
            }
        });
        jMenu5.add(siMhs);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(mnMK, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mnMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510)
                .addComponent(bLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(mnDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(mnMK, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(mnMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(bLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(mnDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMhsMouseClicked
    ListMhs showLMhs= new ListMhs();
    showLMhs.setVisible(true);
    }//GEN-LAST:event_mnMhsMouseClicked

    private void mnMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMKMouseClicked
    MataKuliah showMK = new MataKuliah();
    showMK.setVisible(true);
    }//GEN-LAST:event_mnMKMouseClicked

    private void mnDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDosenMouseClicked
    ListDosen showLDosen = new ListDosen();
    showLDosen.setVisible(true);
    }//GEN-LAST:event_mnDosenMouseClicked

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Selamat Tinggal :) !");
        new login().setVisible(true);
        dispose();

    }//GEN-LAST:event_bgMouseClicked

    private void bLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOutActionPerformed

        int jwb = JOptionPane.showConfirmDialog(this,"Apakah anda yakin akan Log Out dari program ?","Pesan Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        if (jwb == 0){
            new login().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,
                "Welcome Back");
        }
    }//GEN-LAST:event_bLogOutActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    ListMhs showLMhs= new ListMhs();
    showLMhs.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void siDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siDosenActionPerformed
    dosen showDosen = new dosen();
    showDosen.setVisible(true);
    }//GEN-LAST:event_siDosenActionPerformed

    private void siMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siMhsActionPerformed
    mahasiswa showMhs = new mahasiswa();
    showMhs.setVisible(true);
    }//GEN-LAST:event_siMhsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    MataKuliah showMK = new MataKuliah();
    showMK.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    ListDosen showLDosen = new ListDosen();
    showLDosen.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogOut;
    private javax.swing.JLabel bg;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel mnDosen;
    private javax.swing.JLabel mnMK;
    private javax.swing.JLabel mnMhs;
    private javax.swing.JMenuItem siDosen;
    private javax.swing.JMenuItem siMhs;
    // End of variables declaration//GEN-END:variables
}
