/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author IDEAPAD FLEX 5i
 */
public class dosen extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public dosen() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        bJadwal = new javax.swing.JButton();
        bMhs = new javax.swing.JButton();
        bLogOut = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        bJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bJadwal.png"))); // NOI18N
        bJadwal.setMargin(new java.awt.Insets(2, 14, 2, 13));
        bJadwal.setMinimumSize(new java.awt.Dimension(1071, 284));
        bJadwal.setPreferredSize(new java.awt.Dimension(1071, 284));
        bJadwal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bJadwal-pressed.png"))); // NOI18N
        bJadwal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bJadwal-pressed.png"))); // NOI18N
        bJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJadwalActionPerformed(evt);
            }
        });
        getContentPane().add(bJadwal);
        bJadwal.setBounds(160, 580, 1020, 270);

        bMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bMhs.png"))); // NOI18N
        bMhs.setMargin(new java.awt.Insets(2, 14, 2, 13));
        bMhs.setMinimumSize(new java.awt.Dimension(1071, 284));
        bMhs.setPreferredSize(new java.awt.Dimension(1071, 284));
        bMhs.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bMhs-pressed.png"))); // NOI18N
        bMhs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-bMhs-pressed.png"))); // NOI18N
        bMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMhsActionPerformed(evt);
            }
        });
        getContentPane().add(bMhs);
        bMhs.setBounds(160, 280, 1020, 270);

        bLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut.jpg"))); // NOI18N
        bLogOut.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut-pressed.jpg"))); // NOI18N
        bLogOut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bLogOut-pressed.jpg"))); // NOI18N
        bLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(bLogOut);
        bLogOut.setBounds(1570, 340, 80, 60);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen-home.jpg"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOutActionPerformed

        int jwb = JOptionPane.showConfirmDialog(this,"Apakah anda yakin akan Log Out dari program ?","Pesan Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        if (jwb == 0){
            new login().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,
                "Welcome Back");
        }
    }//GEN-LAST:event_bLogOutActionPerformed

    private void bMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMhsActionPerformed
    ListMhs_DS showMhs = new ListMhs_DS();
    showMhs.setVisible(true);
    }//GEN-LAST:event_bMhsActionPerformed

    private void bJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJadwalActionPerformed
    JDKuliah_DS showJDK = new JDKuliah_DS();
    showJDK.setVisible(true);
    }//GEN-LAST:event_bJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton bJadwal;
    private javax.swing.JButton bLogOut;
    private javax.swing.JButton bMhs;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
