/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Frame;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import org.eclipse.persistence.internal.oxm.mappings.Login;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    public login() {
     initComponents();
     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    void log(){
      
      String user = tUser.getText();
      String psw = tPw.getText();
    
        try {          
            koneksiDB.konekDB();
            ResultSet hasil;
            hasil = koneksiDB.retrieveData("SELECT * FROM user WHERE user='"+user+"'AND pass=MD5('"+psw+"')");
        
        if(hasil.next()){    
        
        switch (hasil.getString("level")) {
            case "dosen":
                JOptionPane.showMessageDialog(null,"Welcome Dosen");
                new dosen().setVisible(true);
                dispose();
                break;
            case "mahasiswa":
                JOptionPane.showMessageDialog(null,"Welcome Mahasiswa");
                new mahasiswa().setVisible(true);
                dispose();
                break;
            case "admin":
                JOptionPane.showMessageDialog(null,"Welcome Admin");
                new admin().setVisible(true);
                dispose();
                break;
            default:
                JOptionPane.showMessageDialog(null,"Login Gagal ! !");
                break;
            }     
         
        }else{
                    JOptionPane.showMessageDialog(this, "username atau password salah","ERROR",JOptionPane.WARNING_MESSAGE);
                    tPw.requestFocus();
        }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        
    }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        tUser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        bLogin = new javax.swing.JLabel();
        tPw = new javax.swing.JPasswordField();
        bExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(1120, 520, 590, 20);

        tUser.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        tUser.setBorder(null);
        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });
        getContentPane().add(tUser);
        tUser.setBounds(1120, 472, 590, 60);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(1120, 680, 590, 20);

        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(1101, 750, 630, 90);

        tPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tPw.setBorder(null);
        getContentPane().add(tPw);
        tPw.setBounds(1120, 632, 590, 50);

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bExit.jpg"))); // NOI18N
        bExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bExit-pressed.jpg"))); // NOI18N
        bExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bExit-pressed.jpg"))); // NOI18N
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(1740, 110, 70, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
   
    }//GEN-LAST:event_tUserActionPerformed

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
    log();
    }//GEN-LAST:event_bLoginMouseClicked

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
    int jwb = JOptionPane.showConfirmDialog(this,"Apakah anda yakin akan Exit dari program ?","Pesan Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        if (jwb == 0){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,
                "Welcome Back");
        }
    }//GEN-LAST:event_bExitActionPerformed


        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JLabel bLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField tPw;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
